# 행렬 기초 
- reshape
- concatenate : 병합
- split : 분할
- transpose : 전치행렬
- linalg.inv : 역행렬

In [1]:
import numpy as np

def matrix_tutorial():
    A = np.array([[1,4,5,8],
                    [2,1,7,3],
                    [5,4,5,9]])
    return A
print(matrix_tutorial())


[[1 4 5 8]
 [2 1 7 3]
 [5 4 5 9]]


In [3]:
def matrix_tutorial():
    A = np.array([[1,4,5,8], [2,1,7,3], [5,4,5,9]])
    print('A : \n',A)
    # 1
    B = A.reshape(6,2)
    print('B : \n',B)
    # 2
    B = np.concatenate((B,[[2,2],[5,3]]), axis =0)
    print('reshape B : \n',B)
    # 3
    C,D = np.split(B,2,axis=0)
    print('C :\n' ,C)
    print('D :\n' ,D)
    # 4
    E = np.concatenate((C,D),axis = 1)
    # 5
    return E

print(matrix_tutorial())

A : 
 [[1 4 5 8]
 [2 1 7 3]
 [5 4 5 9]]
B : 
 [[1 4]
 [5 8]
 [2 1]
 [7 3]
 [5 4]
 [5 9]]
reshape B : 
 [[1 4]
 [5 8]
 [2 1]
 [7 3]
 [5 4]
 [5 9]
 [2 2]
 [5 3]]
C :
 [[1 4]
 [5 8]
 [2 1]
 [7 3]]
D :
 [[5 4]
 [5 9]
 [2 2]
 [5 3]]
[[1 4 5 4]
 [5 8 5 9]
 [2 1 2 2]
 [7 3 5 3]]


In [5]:
def matrix_tutorial(A):

    # 2
    B = A.transpose() # 전치행렬 구하기
    print(B)
    try:
        C = np.linalg.inv(B) # 역행렬 구하기
        return np.sum(C > 0)
    except:
        return 'not invertible'
   

def get_matrix():
    # 1
    mat = [] # define mat variable

    first_line = input().strip() # receice first line
    first_line_splitted = first_line.split(" ") # split line by space " "
    n = int(first_line_splitted[0]) # 행의 개수
    m = int(first_line_splitted[1]) # 열의 개수

    for i in range(n):
        line = input().strip() # receive each line ...
        row = line.split(" ")  # ... and split
        for j in range(m):
            row[j] = int(row[j]) # convert to integer
        mat.append(row)

    return np.array(mat)

if __name__ == "__main__":
    A = get_matrix()
    print(matrix_tutorial(A))

2 2
1 2 3 4
5 6 7 8
[['1' '5']
 ['2' '6']
 ['3' '7']
 ['4' '8']]
not invertible
